apiVersion: v1
kind: Pod
metadata:
  name: javawebapp
  labels:
    app: javawebapp
spec:
  containers:
  - name: javawebapp
    image: dockerhandson/java-web-app
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp
spec:
  type: NodePort
  selector: 
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
     
